stages:
  train:
    cmd: python src/Forecasting_System/pipelines/training_pipeline.py
    deps:
      - src/Forecasting_System/pipelines/training_pipeline.py
    outs:
      - artifacts/catboost_main_model.cbm
      - artifacts/catboost_model_10.cbm
      - artifacts/catboost_model_90.cbm
      - artifacts/preprocessor.pkl
